install.packages("rmarkdown")
install.packages("tidyverse") 
install.packages("gt") 
install.packages("gtsummary") 
install.packages("janitor")
install.packages("skimr") 
install.packages("here")
install.packages("scico") 